#! /usr/bin/env -S python3 -u

import sys
import subprocess
import shutil

from pathlib import Path

ROOTDIR = Path(__file__).parent.parent

if (ROOTDIR / 'build/sphinx').exists():
    shutil.rmtree(ROOTDIR / 'build/sphinx')

res = subprocess.run(['sphinx-build', '-M', 'html', '.docbuild', 'build/sphinx'], cwd=ROOTDIR, check=False)
if res.returncode != 0:
    sys.exit(1)
