#! /usr/bin/env -S python3 -u

# pylint: disable=missing-module-docstring, missing-function-docstring, line-too-long

import sys
import re
import subprocess

from pathlib import Path
from datetime import date

MYPATH = Path(__file__).parent
ROOT = MYPATH.parent

NEW_VER = sys.argv[1]

unreleased_link_pattern = re.compile(r"^\[Unreleased\]: (.*)$", re.DOTALL)
lines = []
with open(ROOT / "CHANGELOG.md", "rt", encoding='utf-8') as change_log:
    for line in change_log.readlines():
        # Move Unreleased section to new version
        if re.fullmatch(r"^## Unreleased.*$", line, re.DOTALL):
            lines.append(line)
            lines.append("\n")
            lines.append(
                f"## [{NEW_VER}] - {date.today().isoformat()}\n"
            )
        else:
            lines.append(line)
    lines.append(f'[{NEW_VER}]: https://github.com/gershnik/intrusive_shared_ptr/releases/v{NEW_VER}\n')

with open(ROOT / "CHANGELOG.md", "wt", encoding='utf-8') as change_log:
    change_log.writelines(lines)

(ROOT / "VERSION").write_text(f'{NEW_VER}\n')

readme = (ROOT / 'README.md').read_text()
readme = re.sub(r'`intrusive_shared_ptr/(?:\d+(?:\.\d+)+)`',
                f'`intrusive_shared_ptr/{NEW_VER}`',
                readme)
readme = re.sub(r'GIT_TAG(\s+)v(?:\d+(?:\.\d+)+)',
                fr'GIT_TAG\1v{NEW_VER}',
                readme)
(ROOT / 'README.md').write_text(readme)

subprocess.run(['git', 'add', ROOT / "CHANGELOG.md", ROOT / "VERSION"], check=True)
subprocess.run(['git', 'commit', '-m', f'chore: creating version {NEW_VER}'], check=True)
subprocess.run(['git', 'tag', f'v{NEW_VER}'], check=True)
