name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release Name
        shell: python
        run: |
          import os
          ref = os.environ['GITHUB_REF']
          name = ref[ref.rfind('/') + 2:]
          with open(os.environ['GITHUB_ENV'], 'w') as env:
            print('RELEASE_NAME=' + name, file=env) 

      - name: Zip Headers
        shell: bash
        run: |
          tar -czf intrusive_shared_ptr-${{ env.RELEASE_NAME }}.tar.gz \
                --transform 's/inc/intrusive_shared_ptr\/inc/' \
                --transform 's/modules/intrusive_shared_ptr\/modules/' \
                inc modules

      - name: Make release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: true
          prerelease: false
          name: ${{ env.RELEASE_NAME }}
          body: ...edit me...
          files: |
            intrusive_shared_ptr-${{ env.RELEASE_NAME }}.tar.gz
          
      