name: Test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        cmake -S $GITHUB_WORKSPACE/test -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE 

    - name: Build and Test
      run: cmake --build ${{runner.workspace}}/build --config $BUILD_TYPE --target run-test

