name: Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: |
        cmake -E make_directory build
        cmake -S test -B build -DCMAKE_BUILD_TYPE=Release 

    - name: Build and Test
      run: cmake --build build --config Release --target run-test

